#!/bin/bash
#-------------------------------------------------------------------
# ispc-initial
#-------------------------------------------------------------------
# ISPC Kit - ISPConfig 3 Installer
#
# File:         ispc-initial
# Author:       Ragdata
# Date:         26/02/2021 1527
# License:      MIT License
# Copyright:    2021 ~ Aequitas Veritas Pty Ltd ~ All Rights Reserved
#-------------------------------------------------------------------
# PERFORM COMPATIBILITY CHECKS
#-------------------------------------------------------------------
if [ "${BASH_VERSION:0:1}" -lt 4 ]; then
    echo "ISPC Kit requires a minimum Bash version of 4 - you need to upgrade before you can use this package."
    return 1
fi
#-------------------------------------------------------------------
# LOAD LIBRARIES
#-------------------------------------------------------------------
baseDir=$PWD
. "$baseDir"/src/inc/common.sh
. "$incDir"/functions.sh
. "$incDir"/registry.sh
#-------------------------------------------------------------------
# INIT
#-------------------------------------------------------------------
# if no .defaults file, copy the .defaults.dist file in its place
if [[ ! -f "$DEF" ]] && [[ -f "$DIS" ]]; then cp "$DIS" "$DEF"; fi
# load .defaults
. "$DEF"
# if no .registry file, build it, otherwise load it
if [[ ! -f "$REG" ]]; then initLog registry; buildRegistry; else . "$REG"; fi
#-------------------------------------------------------------------
# GET ARGS
#-------------------------------------------------------------------
if [[ $# ]]; then
    if [[ $# -ge 1 ]] && [[ $1 =~ $isLoc ]]; then REGISTRY[LOC]=$1; shift; fi
else
    REGISTRY[LOC]=${DEFAULTS[LOC]}
fi
if [[ $# ]] && [[ $1 =~ $isFlag ]]; then
    case $1 in
        "-h"|"-help")   flag="help";;
        "-t"|"-test")   flag="test";;
    esac
    shift
fi
#-------------------------------------------------------------------
# MAIN
#-------------------------------------------------------------------
clear
# display help file?
if [[ $flag == "help" ]]; then cat "$docsDir"/.helpinit; return 0; fi
# check if system initialised
if [ -n "${REGISTRY[INIT]}" ]; then errorExit "ERROR: System is already initialised!"; fi
# initalise system
loadSource "$libDir/init"
loadSource "$libDir/swap"
REGISTRY[INIT]=1
writeRegistry
echoLog "Initialisation complete - You should reboot the server now"
