name: Test on Push

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches: [ master ]

  workflow_dispatch:

jobs:

  tests:
    name: ISPC-Kit Self Tests
    runs-on: self-hosted
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Execute Custom Tests
        run: |
          cd test
          sudo . test_libs.sh
